[package]
name = "kdbx"
version = "0.1.0"
authors = ["Loren M. Lang <lorenl@north-winds.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.2"
uuid = "0.8.1"
ring = "0.16.9"
rpassword = "4.0.3"
openssl = "0.10.26"
flate2 = "1.0.13"
sxd-document = "0.3.2"
sxd-xpath = "0.4.2"
base64 = "0.11.0"
chrono = "0.4.10"
hex = "0.4.0"
